#!/bin/bash
DATABASE_FQDN=$1
MANAGED_IDENTITY_NAME=$2
DATABASE_NAME=$3
DATABASE_USER=$4
DATABASE_USER_PASSWORD=$5

sqlcmd -S "${DATABASE_FQDN}" -d "${DATABASE_NAME}" -U "${DATABASE_USER}" -P "${DATABASE_USER_PASSWORD}" -l 30 <<EOF
CREATE USER [${MANAGED_IDENTITY_NAME}] FROM EXTERNAL PROVIDER;
ALTER ROLE db_datareader ADD MEMBER [${MANAGED_IDENTITY_NAME}];
ALTER ROLE db_datawriter ADD MEMBER [${MANAGED_IDENTITY_NAME}];
ALTER ROLE db_ddladmin ADD MEMBER [${MANAGED_IDENTITY_NAME}];
GO
EOF